<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>50cad339-c3f4-43a9-bca3-4a5335fd3839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[16]/div/a[5]/i/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>275788db-beaa-4e15-be6b-7d35e758a59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appNav&quot;]/div[@class=&quot;appNav__panel&quot;]/a[@class=&quot;appNav__item&quot;]/i[1]/span[1]</value>
      <webElementGuid>eec18824-2cef-4c89-88d4-c25aa99ddd28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[16]/div/a[5]/i/span</value>
      <webElementGuid>5a461224-091c-4e18-a60e-70a1add686bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/i/span</value>
      <webElementGuid>7dd3ea2b-ccd3-4f9f-96f7-8c535191263d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
