<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>c767b59b-0d7f-4689-82ac-11be70838193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[3]/div[2]/div/div[2]/a/i/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a598f0d3-be37-41a6-b3f5-e2b8ab957bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;bankLists&quot;]/div[@class=&quot;bankList&quot;]/div[@class=&quot;bankList__body&quot;]/div[@class=&quot;bankList__dropdown&quot;]/a[@class=&quot;bankList__dropdown__toggle&quot;]/i[1]/span[1]</value>
      <webElementGuid>cfbf10a5-f5b8-45b4-9f80-ca7b760acdd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div[2]/div/div[2]/a/i/span</value>
      <webElementGuid>62b3f5a1-59b0-4d52-a1b1-79746aa9eca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a/i/span</value>
      <webElementGuid>5e4d89db-9062-43af-9438-f07badcd4231</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
