<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>20eff060-6b32-4f74-ba62-ac0e8eab52dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-7570 > a.elementor-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-1-3fa60b2']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>460957f6-78a6-4c9a-968d-0c2894af8f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://evermos.com/login</value>
      <webElementGuid>0db1cd35-ac32-4a76-b3dc-c238d566d121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-item</value>
      <webElementGuid>17c0eaf1-dfdd-48ff-b586-639d33a28b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>d9f1e48d-7bd5-4a54-8ea1-2818030d79f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents flexbox&quot;]/body[@class=&quot;home page-template page-template-elementor_header_footer page page-id-14034 custom-background header-inactive footer-inactive elementor-default elementor-template-full-width elementor-kit-117 elementor-page elementor-page-14034 e--ua-firefox&quot;]/div[@class=&quot;elementor elementor-14439 elementor-location-header&quot;]/div[@class=&quot;elementor-section-wrap&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-679147c elementor-section-full_width elementor-section-stretched elementor-section-height-default elementor-section-height-default elementor-sticky elementor-sticky--active elementor-section--handles-inside elementor-sticky--effects jet-parallax-section&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7754095&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-20ce986 elementor-section-boxed elementor-section-height-default elementor-section-height-default jet-parallax-section&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-4079737&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/div[@class=&quot;elementor-element elementor-element-3fa60b2 elementor-nav-menu__align-right elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu&quot;]/div[@class=&quot;elementor-widget-container&quot;]/nav[@class=&quot;elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-none&quot;]/ul[@id=&quot;menu-1-3fa60b2&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-7570&quot;]/a[@class=&quot;elementor-item&quot;]</value>
      <webElementGuid>603b8d0d-4fd9-414c-8536-a42b6daf993a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-1-3fa60b2']/li/a</value>
      <webElementGuid>02d0d3c6-c8c4-4955-9378-399a2acf41bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>ae23c818-9608-4144-aac0-897c20113e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mofasa'])[2]/following::a[1]</value>
      <webElementGuid>8c04c7ff-d8ae-46bc-865c-0c366ce5991c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everpro'])[2]/following::a[2]</value>
      <webElementGuid>f0ef1e8b-fb1f-453d-8274-72bec6d9b517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>509f6417-a756-4bfc-8d16-c7c86a3144d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[2]</value>
      <webElementGuid>8bb83a52-995c-46c8-ae01-c2b2b45f64a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>ef77a38d-2aa8-4efa-b347-f760209d0f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://evermos.com/login')]</value>
      <webElementGuid>fdc4b835-1b6d-45b8-ac2f-e1a8bcdd12bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/nav/ul/li/a</value>
      <webElementGuid>fe5e7a36-da98-48a5-87c5-69e9f328aeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://evermos.com/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>d9d0e071-ca30-4eef-adb6-f64d61862028</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
