<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Filter</name>
   <tag></tag>
   <elementGuidId>e21cb066-1003-46f8-a1ad-24437d7ae84d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.td-none.bg-white.flex.items-center.px-12.py-8.br-4.my-8.ml-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ecd4d13-6679-4188-a568-bdfa69990be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9763f691-07df-4591-903f-b0171a029c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8</value>
      <webElementGuid>4a1f36a5-308a-4095-b74e-60b827f154ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter   </value>
      <webElementGuid>5ef875a5-2018-427a-9cd7-bf7453039280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[2]/div[@class=&quot;flex items-start&quot;]/a[@class=&quot;td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8&quot;]</value>
      <webElementGuid>803f9c25-4cba-43ad-b9f1-486d901183af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cfa500c-41db-4f38-a5d0-7c9ba243ce55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5e6b8239-4e27-4322-9ba3-90505f812a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8</value>
      <webElementGuid>e6946986-14d1-4123-a8b4-b0840256535e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter   </value>
      <webElementGuid>de6142bb-9d93-4b0a-aa80-18e5d3439a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[2]/div[@class=&quot;flex items-start&quot;]/a[@class=&quot;td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8&quot;]</value>
      <webElementGuid>091cfa55-5ea3-4285-bf4a-413c1e7ca103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a55b10d-4e13-4178-a1bd-04a9090471c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c1714dd0-c628-4a67-8513-64397e8247d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8</value>
      <webElementGuid>9340b29d-956f-4f04-b49b-687fbede2052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter   </value>
      <webElementGuid>e616a42e-58c2-48b1-b03b-2691bdc7859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[2]/div[@class=&quot;flex items-start&quot;]/a[@class=&quot;td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8&quot;]</value>
      <webElementGuid>6dcd03af-714a-4474-82ba-472dea106e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b1af466c-bdb1-4a9a-8856-0b99b0950117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3391c7cd-3852-4ad4-861e-2359a1474a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8</value>
      <webElementGuid>ec7e7287-e01d-4f9e-8fd5-161656bb9cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter   </value>
      <webElementGuid>8ef59ff0-3077-49e3-b271-c5e8306305cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[2]/div[@class=&quot;flex items-start&quot;]/a[@class=&quot;td-none bg-white flex items-center px-12 py-8 br-4 my-8 ml-8&quot;]</value>
      <webElementGuid>e4540395-e9fb-44d3-8898-0070a46d0dec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[2]/div/a</value>
      <webElementGuid>ffec594d-6c00-444f-940b-5e726e42725f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::a[4]</value>
      <webElementGuid>dcefbbd9-d0af-488f-8cdf-c00bdb13a684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berbagai keuntungan bisa kamu dapatkan di Aplikasi Evermos.'])[1]/following::a[4]</value>
      <webElementGuid>712a5545-cfdd-4296-8c05-06042fc566a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jawa Barat'])[1]/preceding::a[1]</value>
      <webElementGuid>17eec4a9-6fc2-4e62-a4af-b05e001e8c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>336fb0bd-c19a-4705-81d3-5d6492a762e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>1556853a-f7c4-44f7-aa40-55cc4a3ca485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Filter   ' or . = 'Filter   ')]</value>
      <webElementGuid>5c459a03-99eb-440f-80a0-462eef883388</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
