<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Rp1.261.001</name>
   <tag></tag>
   <elementGuidId>353086fb-e4e2-4cd0-aa6c-385f7089deac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.productCard__price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43d80e35-4048-46e6-b6da-7a41ebec28e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__price</value>
      <webElementGuid>7e97e1dd-b997-43c3-884c-16733c98d384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp1.261.001</value>
      <webElementGuid>cacbbeb2-151b-472c-b2dd-e5530fce3b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;productItems&quot;]/div[@class=&quot;productItems__row&quot;]/div[@class=&quot;productItems__cell&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__body&quot;]/div[@class=&quot;productCard__price&quot;]</value>
      <webElementGuid>afef8929-911b-4c4c-ab9b-8e9c80b46981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b483c3f-e877-41e3-9362-9f62e9373d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>productCard__price</value>
      <webElementGuid>60f1e372-a956-45d5-a503-5f0c8b74eefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp1.261.001</value>
      <webElementGuid>c57d97df-1ea9-4b2b-90ac-fbcb7ebbbaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appSection&quot;]/div[@class=&quot;productItems&quot;]/div[@class=&quot;productItems__row&quot;]/div[@class=&quot;productItems__cell&quot;]/div[@class=&quot;productCard&quot;]/div[@class=&quot;productCard__body&quot;]/div[@class=&quot;productCard__price&quot;]</value>
      <webElementGuid>c434dc30-ecf6-4fff-89e2-a46b76928049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[4]/div/div/div/div/div[2]/div[4]</value>
      <webElementGuid>ad85b92f-3ee6-4866-a147-54fb3f641d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Reseller'])[1]/following::div[1]</value>
      <webElementGuid>7f2431d3-c4ed-4e35-834a-b1605e70e49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Andina Nursing Wear Gamis rayon menyusui bukaan samping 10 piece'])[1]/following::div[2]</value>
      <webElementGuid>a5db6c30-5dee-499d-8c70-ad60acc9568d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagikan Produk'])[1]/preceding::div[1]</value>
      <webElementGuid>1fc392dd-3aea-47d1-9c8e-123ff9225bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KOMISI'])[2]/preceding::div[3]</value>
      <webElementGuid>6213175f-45b4-4f68-863a-7810faa6d473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp1.261.001']/parent::*</value>
      <webElementGuid>842a6ca3-e255-41fd-9fd4-8e94826302b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
      <webElementGuid>024d9b4f-eb56-4987-955d-0748d0bb21d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Rp1.261.001' or . = 'Rp1.261.001')]</value>
      <webElementGuid>36a35dac-061e-4159-9a35-817189337b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
