<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_inputText__input</name>
   <tag></tag>
   <elementGuidId>78b51423-c60b-4ca7-aaac-7c03b94da07f</elementGuidId>
   <imagePath>Screenshots/Targets/Page_Evermos/input_Rp_inputText__input.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.inputText.inputText--focus.inputText--filled > span.inputText__inner > input.inputText__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='money'])[2]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_Evermos/input_Rp_inputText__input.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea4a15a2-b536-4599-85be-561b666ecba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>929d7ec4-03b9-45f5-8022-efeb1b6939d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText__input</value>
      <webElementGuid>6c1d169d-6846-4149-bbd2-e8c7a781ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[3]/div[@class=&quot;productFilter&quot;]/div[@class=&quot;productFilter__panel&quot;]/div[@class=&quot;productFilter__wrapper&quot;]/div[@class=&quot;productFilter__section mt-4&quot;]/div[@class=&quot;productFilter__body&quot;]/div[@class=&quot;productFilter__prices&quot;]/div[@class=&quot;productFilter__price&quot;]/label[@class=&quot;inputText inputText--focus inputText--filled&quot;]/span[@class=&quot;inputText__inner&quot;]/input[@class=&quot;inputText__input&quot;]</value>
      <webElementGuid>ce32e63d-6522-48ca-8486-f9596179c24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cba37a7-ed56-4683-b06e-19f4f154b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>4009bd58-f948-41b5-b85f-daf8f11482c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText__input</value>
      <webElementGuid>2d3e7fb5-a738-4bb8-b1c1-e34a9d5b375c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[3]/div[@class=&quot;productFilter&quot;]/div[@class=&quot;productFilter__panel&quot;]/div[@class=&quot;productFilter__wrapper&quot;]/div[@class=&quot;productFilter__section mt-4&quot;]/div[@class=&quot;productFilter__body&quot;]/div[@class=&quot;productFilter__prices&quot;]/div[@class=&quot;productFilter__price&quot;]/label[@class=&quot;inputText inputText--focus inputText--filled&quot;]/span[@class=&quot;inputText__inner&quot;]/input[@class=&quot;inputText__input&quot;]</value>
      <webElementGuid>a51c7841-d3d8-49ce-9a32-0ca970d473df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfc5b01b-e851-43fa-bd32-03f6ee2d4bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>money</value>
      <webElementGuid>71fb4134-0650-437b-9eff-09cfcd2c462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputText__input</value>
      <webElementGuid>de663350-4143-4f6f-8343-fa731361e318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[3]/div[@class=&quot;productFilter&quot;]/div[@class=&quot;productFilter__panel&quot;]/div[@class=&quot;productFilter__wrapper&quot;]/div[@class=&quot;productFilter__section mt-4&quot;]/div[@class=&quot;productFilter__body&quot;]/div[@class=&quot;productFilter__prices&quot;]/div[@class=&quot;productFilter__price&quot;]/label[@class=&quot;inputText inputText--focus inputText--filled&quot;]/span[@class=&quot;inputText__inner&quot;]/input[@class=&quot;inputText__input&quot;]</value>
      <webElementGuid>0d32cd20-9025-4444-8c90-87b38294ba8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='money'])[2]</value>
      <webElementGuid>043ebd43-8fdc-4d4e-b447-26d2a8174c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[3]/div/div/div[2]/div[2]/div[2]/div/div[2]/label/span[2]/input</value>
      <webElementGuid>aa87888b-017b-46f4-a939-07cbd74d82c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span[2]/input</value>
      <webElementGuid>b452abb1-659e-4f2d-be32-08dbed54c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'money']</value>
      <webElementGuid>815fe723-f51d-4e00-b85c-50fe785d48b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
