<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>28d12600-3f8a-4f21-bb27-573c04a79383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div[3]/a[2]/i/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe7b0a7d-3853-40ac-b665-86d8817ab89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[@class=&quot;appLayoutHeading__panel shadow&quot;]/div[@class=&quot;appLayoutHeading__actions appLayoutHeading__actions--right&quot;]/a[@class=&quot;appLayoutHeading__button&quot;]/i[1]/span[1]</value>
      <webElementGuid>9427d924-a35c-40e9-b19f-f45f8752d4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0f851861-47fb-42ea-b94f-99c5f6db13c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;appLayout&quot;]/div[@class=&quot;appLayoutHeading&quot;]/div[@class=&quot;appLayoutHeading__panel shadow&quot;]/div[@class=&quot;appLayoutHeading__actions appLayoutHeading__actions--right&quot;]/a[@class=&quot;appLayoutHeading__button&quot;]/i[1]/span[1]</value>
      <webElementGuid>f587583a-6508-4949-ad49-8724840cdbe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div[3]/a[2]/i/span</value>
      <webElementGuid>65367c68-dcc0-4bb8-a991-7dac93989b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i/span</value>
      <webElementGuid>74727aa3-103d-423b-a8f6-28473b0001db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div[2]/a[2]/i/span</value>
      <webElementGuid>4323aa64-b0bd-4144-a9c2-1f48f1baa108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
