<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>9f530cef-511d-4c90-ac65-e007b0099f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-7570 > a.elementor-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-1-3fa60b2']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88712461-4e1e-405c-a03a-1928b2d6e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://evermos.com/login</value>
      <webElementGuid>214c8337-ba81-40b5-9a42-4a9c4b41ce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-item</value>
      <webElementGuid>11d7b123-6d78-4972-8b02-e9a928ddab07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>1313105a-afd9-4056-bbe3-fc345a78755b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touchevents flexbox&quot;]/body[@class=&quot;home page-template page-template-elementor_header_footer page page-id-14034 custom-background header-inactive footer-inactive elementor-default elementor-template-full-width elementor-kit-117 elementor-page elementor-page-14034 e--ua-firefox&quot;]/div[@class=&quot;elementor elementor-14439 elementor-location-header&quot;]/div[@class=&quot;elementor-section-wrap&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-679147c elementor-section-full_width elementor-section-stretched elementor-section-height-default elementor-section-height-default elementor-sticky elementor-sticky--active elementor-section--handles-inside elementor-sticky--effects jet-parallax-section&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-100 elementor-top-column elementor-element elementor-element-7754095&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/section[@class=&quot;elementor-section elementor-inner-section elementor-element elementor-element-20ce986 elementor-section-boxed elementor-section-height-default elementor-section-height-default jet-parallax-section&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-row&quot;]/div[@class=&quot;elementor-column elementor-col-33 elementor-inner-column elementor-element elementor-element-4079737&quot;]/div[@class=&quot;elementor-column-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-widget-wrap&quot;]/div[@class=&quot;elementor-element elementor-element-3fa60b2 elementor-nav-menu__align-right elementor-nav-menu--dropdown-none elementor-widget elementor-widget-nav-menu&quot;]/div[@class=&quot;elementor-widget-container&quot;]/nav[@class=&quot;elementor-nav-menu--main elementor-nav-menu__container elementor-nav-menu--layout-horizontal e--pointer-none&quot;]/ul[@id=&quot;menu-1-3fa60b2&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-7570&quot;]/a[@class=&quot;elementor-item&quot;]</value>
      <webElementGuid>508f7156-fcdc-473b-85c3-64b55456bdbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-1-3fa60b2']/li/a</value>
      <webElementGuid>0fc9f9ec-9302-44c7-9056-6e09237eaeb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>c07b812c-0d6c-449b-b2bd-234032f135e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mofasa'])[2]/following::a[1]</value>
      <webElementGuid>6bd623b6-ba92-4fff-9710-7dd9b34113f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everpro'])[2]/following::a[2]</value>
      <webElementGuid>163f6f1f-e808-4f88-a191-5e68e8ff747a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>a651e35e-e04b-4f24-b7dd-463e5c48706e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[2]/preceding::a[2]</value>
      <webElementGuid>298bf385-59e5-47e1-9533-ad36e606a0d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://evermos.com/login')]</value>
      <webElementGuid>b0d4742f-229c-452f-af9a-4ca340a1f8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/nav/ul/li/a</value>
      <webElementGuid>9b44979d-39aa-4def-9795-601ac059f528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://evermos.com/login' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>ef15eb2a-f346-4917-b621-132b9dadf93d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
